import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { artClipFrames, parseArtIndex, parseArtPack, type ArtAtlas, type ArtIndexEntry, type ArtIssue, type ArtPack } from '../../src/presentation/artManifest';
import { inspectPicture, pictureIssues } from './inspect';
import { atlasJson, DEFAULT_PACK, packFrames, type PackOptions, type SourceFrame } from './pack';
import { decodePng, encodePng, readPngInfo, type PngInfo, type RgbaImage } from './png';
import { extractSheet } from './sheet';
import { verifyArt, verifyArtFolder } from './verify';

/**
 * THE ART BUILD (docs/ART-PIPELINE-2D.md, part C): `art/` — what the artist hands over, committed, never served — in; `public/art/` — what the game fetches,
 * generated, never edited by hand — out.
 *
 *   art/index.json                         which packs there are, their category, when each one loads (`boot`, `zone` + rooms, `lazy`)
 *   art/<pack>/<pack>.pack.json            the manifest of the pack: its sprite sets (scale, pivot, clips, anchors, tags). No `atlases`: the packer writes them
 *   art/<pack>/<sprite>/<frame>.png        one PNG per frame, named as the clips say (`idle_00.png` … for the clip `idle` with `frames: "idle_"`)
 *
 * A pack that already carries its atlases (the artist packed them with their own tool: `atlases` lists images and JSON) is copied as it is, byte for byte,
 * after the same checks. A pack whose `status` is `awaiting-art` is the contract of art that has not been handed over yet: it is checked, it is reported,
 * and it is NOT shipped — a game with no art fetches nothing.
 *
 * Everything is computed in memory first and written only if nothing is an error: a failed build leaves `public/art/` as it was.
 */
export interface BuildOptions {
  srcDir: string;
  outDir: string;
  /** `false` checks everything and writes nothing (`npm run assets:check`). */
  write: boolean;
  pack?: Partial<PackOptions>;
}

export interface BuiltSprite {
  id: string;
  frames: number;
  stored: number;
  pages: number;
  /** Pixels of its pages and what they weigh once decoded (RGBA8) and on disk. */
  pagePixels: number;
}

export interface BuiltPack {
  id: string;
  status: string;
  shipped: boolean;
  how: 'packed' | 'copied' | 'awaiting';
  sprites: BuiltSprite[];
}

export interface BuildResult {
  ok: boolean;
  packs: BuiltPack[];
  issues: ArtIssue[];
  /** Files written (relative to `outDir`), in order. */
  written: string[];
  /** Bytes of the files that ship, and the memory their images take decoded. */
  diskBytes: number;
  decodedBytes: number;
}

/** The first line of `README.txt` in the folder the build writes: what says "this folder is generated and may be rewritten". */
export const GENERATED_MARKER = 'Generated by `npm run assets:pack` from art/ — do not edit by hand.';

interface Output {
  rel: string;
  data: Buffer | string;
}

const json = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`;

function readJson(file: string, label: string, issues: ArtIssue[]): unknown {
  try {
    return JSON.parse(readFileSync(file, 'utf8')) as unknown;
  } catch (err) {
    issues.push({ level: 'error', path: label, message: `cannot be read as JSON (${err instanceof Error ? err.message : String(err)})` });
    return undefined;
  }
}

/** The folder of a pack's manifest (posix, relative to the index): where its atlases ship, because every path in the manifest is relative to it. */
const folderOf = (manifest: string): string => manifest.slice(0, Math.max(0, manifest.lastIndexOf('/')));
const under = (folder: string, file: string): string => (folder === '' ? file : `${folder}/${file}`);

const tagged = (label: string, issues: readonly ArtIssue[]): ArtIssue[] => issues.map((i) => ({ ...i, path: i.path ? `${label} ${i.path}` : label }));

/** Packs the frames of every sprite set of a pack that is given as folders of PNGs. */
function packFolders(entry: ArtIndexEntry, packDir: string, outFolder: string, raw: Record<string, unknown>, opts: Partial<PackOptions>, issues: ArtIssue[]): { atlases: ArtAtlas[]; sprites: unknown[]; outputs: Output[]; built: BuiltSprite[]; pack: ArtPack | null } {
  const label = entry.id;
  const outputs: Output[] = [];
  const built: BuiltSprite[] = [];
  const atlases: ArtAtlas[] = [];
  // the sprite sets as the manifest declares them, with the atlases left out: that is what the packer fills
  const relaxed = parseArtPack({ ...raw, status: 'awaiting-art', atlases: [], sprites: ((raw['sprites'] as unknown[] | undefined) ?? []).map((s) => ({ ...(s as object), atlases: [] })) });
  issues.push(...tagged(label, relaxed.issues.filter((i) => i.level === 'error')));
  if (!relaxed.value) return { atlases, sprites: [], outputs, built, pack: null };
  const rawSprites = (raw['sprites'] as Array<Record<string, unknown>>) ?? [];
  const spritesOut: unknown[] = [];
  const claimed = new Map<string, string>();
  const dir = (id: string): string => join(packDir, id);

  relaxed.value.sprites.forEach((sprite, index) => {
    const frames: SourceFrame[] = [];
    // what the pictures say about themselves (no transparency, nothing visible, cut at the edge), said ONCE per message for the whole set, not once per frame
    const said = new Map<string, { level: ArtIssue['level']; message: string; frames: string[] }>();
    const examine = (name: string, image: RgbaImage, info: Pick<PngInfo, 'hasAlpha'>): void => {
      for (const i of pictureIssues(`${sprite.id}/${name}.png`, inspectPicture(image, info), entry.category, sprite.pivot[1])) {
        const key = `${i.level}|${i.message}`;
        said.set(key, { level: i.level, message: i.message, frames: [...(said.get(key)?.frames ?? []), `${name}.png`] });
      }
    };
    // frames that come from a spritesheet cut by a grid the manifest states (a crop: nothing is resampled)
    const fromSheet = new Map<string, { image: RgbaImage; sheet: string; info: PngInfo }>();
    const sheets = rawSprites[index]?.['sheets'];
    if (sheets !== undefined && !Array.isArray(sheets)) issues.push({ level: 'error', path: `${label} sprites.${sprite.id}.sheets`, message: 'must be a list of sheets' });
    for (const [k, rawSheet] of (Array.isArray(sheets) ? sheets : []).entries()) {
      const at = `${label} sprites.${sprite.id}.sheets[${k}]`;
      const name = typeof (rawSheet as { file?: unknown } | null)?.file === 'string' ? (rawSheet as { file: string }).file : '';
      const file = join(dir(sprite.id), name);
      if (!/^[A-Za-z0-9][A-Za-z0-9_.-]*\.png$/.test(name) || !existsSync(file)) {
        issues.push({ level: 'error', path: at, message: name ? `the sheet ${sprite.id}/${name} is not there` : 'needs a "file"' });
        continue;
      }
      try {
        const bytes = readFileSync(file);
        const info = readPngInfo(bytes, true);
        const cut = extractSheet(rawSheet, decodePng(bytes));
        for (const e of cut.errors) issues.push({ level: 'error', path: at, message: e });
        for (const f of cut.frames) {
          if (fromSheet.has(f.name)) issues.push({ level: 'error', path: at, message: `frame "${f.name}" is also cut by sheet ${fromSheet.get(f.name)!.sheet}` });
          else fromSheet.set(f.name, { image: f.image, sheet: name, info });
        }
      } catch (err) {
        issues.push({ level: 'error', path: at, message: `${name}: ${err instanceof Error ? err.message : String(err)}` });
      }
    }
    const wanted = new Map<string, string>(); // frame name → the clip that asks for it
    for (const [state, clip] of Object.entries(sprite.clips)) for (const name of artClipFrames(clip!)) if (!wanted.has(name)) wanted.set(name, state);
    for (const [name, state] of wanted) {
      const owner = claimed.get(name);
      if (owner !== undefined && owner !== sprite.id) {
        issues.push({ level: 'error', path: `${label} sprites.${sprite.id}.clips.${state}`, message: `frame name "${name}" is also used by sprite set "${owner}": the pages of a pack name each frame once (give the clips of each set their own prefix)` });
        continue;
      }
      claimed.set(name, sprite.id);
      const file = join(dir(sprite.id), `${name}.png`);
      const cut = fromSheet.get(name);
      if (existsSync(file) && cut) {
        issues.push({ level: 'error', path: `${label} sprites.${sprite.id}.clips.${state}`, message: `frame "${name}" is both a file (${sprite.id}/${name}.png) and a cell of sheet ${cut.sheet}: say it once` });
        continue;
      }
      if (cut) {
        examine(name, cut.image, cut.info);
        frames.push({ name, image: cut.image });
        continue;
      }
      if (!existsSync(file)) {
        issues.push({ level: 'error', path: `${label} sprites.${sprite.id}.clips.${state}`, message: `missing frame file ${sprite.id}/${name}.png (or a sheet that cuts it)` });
        continue;
      }
      try {
        const bytes = readFileSync(file);
        const info = readPngInfo(bytes, true);
        if (info.bitDepth === 16) issues.push({ level: 'info', path: `${label} ${sprite.id}/${name}.png`, message: 'is 16 bits per channel: the GPU has 8, so its values were rounded to 8' });
        if (info.colourChunks.includes('iCCP')) issues.push({ level: 'warn', path: `${label} ${sprite.id}/${name}.png`, message: 'carries an embedded colour profile (iCCP): the pixel numbers are used as they are, the profile is not carried over — export as sRGB so that nothing shifts' });
        const image = decodePng(bytes);
        examine(name, image, info);
        frames.push({ name, image });
      } catch (err) {
        issues.push({ level: 'error', path: `${label} ${sprite.id}/${name}.png`, message: err instanceof Error ? err.message : String(err) });
      }
    }
    for (const m of said.values()) {
      const shown = `${m.frames.slice(0, 4).join(', ')}${m.frames.length > 4 ? ', …' : ''}`;
      issues.push({ level: m.level, path: `${label} sprites.${sprite.id}`, message: `${m.frames.length === 1 ? shown : `${m.frames.length} frames (${shown})`} ${m.message}` });
    }
    // the folder may hold frames no clip uses: they are not packed, and the artist is told
    const folder = existsSync(dir(sprite.id)) ? readdirSync(dir(sprite.id)).filter((f) => f.toLowerCase().endsWith('.png')) : [];
    const sheetFiles = new Set([...fromSheet.values()].map((c) => c.sheet));
    const unused = [...folder.filter((f) => !wanted.has(f.slice(0, -4)) && !sheetFiles.has(f)), ...[...fromSheet.keys()].filter((n) => !wanted.has(n)).map((n) => `${n} (of a sheet)`)];
    if (unused.length > 0) issues.push({ level: 'warn', path: `${label} sprites.${sprite.id}`, message: `${unused.length} frame file(s) no clip uses (${unused.slice(0, 3).join(', ')}${unused.length > 3 ? ', …' : ''}): they are not packed` });
    if (frames.length === 0 || frames.length < wanted.size) return; // what is missing was reported; nothing is packed for a set that is not whole

    const sizes = new Set(frames.map((f) => `${f.image.width} × ${f.image.height}`));
    if (sizes.size > 1) {
      issues.push({ level: 'error', path: `${label} sprites.${sprite.id}`, message: `its frames are not all the same size (${[...sizes].join(', ')}): the pivot is a fraction of the frame, so every frame of a set must be drawn on the same canvas` });
      return;
    }
    try {
      const packed = packFrames(frames, opts);
      const ids: string[] = [];
      packed.pages.forEach((page, n) => {
        const id = `${sprite.id}_${n}`;
        const png = encodePng(page.image);
        outputs.push({ rel: under(outFolder, `${id}.png`), data: png }, { rel: under(outFolder, `${id}.json`), data: json(atlasJson(packed, n, `${id}.png`)) });
        atlases.push({ id, source: `${id}.png`, data: `${id}.json`, width: page.image.width, height: page.image.height, resolution: 1 });
        ids.push(id);
      });
      built.push({ id: sprite.id, frames: frames.length, stored: packed.stats.stored, pages: packed.pages.length, pagePixels: packed.stats.pagePixels });
      const { sheets: _sheets, ...shipped } = rawSprites[index] ?? {};
      void _sheets; // the grid is how the frames were cut, not something the game needs: it does not ship
      spritesOut.push({ ...shipped, atlases: ids });
    } catch (err) {
      issues.push({ level: 'error', path: `${label} sprites.${sprite.id}`, message: err instanceof Error ? err.message : String(err) });
    }
  });
  return { atlases, sprites: spritesOut, outputs, built, pack: relaxed.value };
}

/** Builds one pack. `outputs` are the files it writes, relative to the output folder. */
function buildPack(entry: ArtIndexEntry, srcDir: string, opts: Partial<PackOptions>, issues: ArtIssue[]): { built: BuiltPack; outputs: Output[]; manifest: string | null } {
  const label = entry.id;
  const manifestFile = join(srcDir, ...entry.manifest.split('/'));
  const packDir = dirname(manifestFile);
  const none = (how: BuiltPack['how'], status: string, shipped = false): { built: BuiltPack; outputs: Output[]; manifest: string | null } => ({ built: { id: entry.id, status, shipped, how, sprites: [] }, outputs: [], manifest: null });
  if (!existsSync(manifestFile)) {
    issues.push({ level: 'error', path: label, message: `its manifest ${entry.manifest} is not there` });
    return none('packed', 'unknown');
  }
  const raw = readJson(manifestFile, `${label} ${entry.manifest}`, issues);
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) {
    if (raw !== undefined) issues.push({ level: 'error', path: `${label} ${entry.manifest}`, message: 'must be an object' });
    return none('packed', 'unknown');
  }
  const rawPack = raw as Record<string, unknown>;
  const status = typeof rawPack['status'] === 'string' ? rawPack['status'] : 'final';
  const outFolder = folderOf(entry.manifest);

  // the contract of art not handed over yet: checked, reported, not shipped
  if (status === 'awaiting-art') {
    // the sprite sets of a pack that has no images yet carry no atlases: that is what "awaiting" says
    const parsed = parseArtPack({ ...rawPack, atlases: [], sprites: ((rawPack['sprites'] as unknown[] | undefined) ?? []).map((s) => ({ ...(s as object), atlases: [] })) });
    issues.push(...tagged(label, parsed.issues.filter((i) => i.level !== 'info')));
    return none('awaiting', status);
  }

  const declared = Array.isArray(rawPack['atlases']) ? (rawPack['atlases'] as unknown[]) : [];
  let outputs: Output[] = [];
  let manifestOut: Record<string, unknown>;
  let sprites: BuiltSprite[] = [];
  let how: BuiltPack['how'];
  if (declared.length > 0) {
    // packed by the artist's own tool: copied as it is, byte for byte
    how = 'copied';
    manifestOut = rawPack;
    const parsed = parseArtPack(rawPack);
    for (const a of parsed.value?.atlases ?? []) {
      for (const rel of [a.source, ...(a.data ? [a.data] : [])]) {
        const file = join(packDir, ...rel.split('/'));
        if (!existsSync(file)) issues.push({ level: 'error', path: `${label} atlases.${a.id}`, message: `${rel} is not there` });
        else outputs.push({ rel: under(outFolder, rel), data: readFileSync(file) });
      }
    }
  } else {
    how = 'packed';
    const packed = packFolders(entry, packDir, outFolder, rawPack, opts, issues);
    outputs = packed.outputs;
    sprites = packed.built;
    if (!packed.pack || packed.sprites.length !== packed.pack.sprites.length) return { built: { id: entry.id, status, shipped: false, how, sprites }, outputs: [], manifest: null };
    manifestOut = { ...rawPack, atlases: packed.atlases, sprites: packed.sprites };
  }

  return { built: { id: entry.id, status, shipped: true, how, sprites }, outputs, manifest: json(manifestOut) };
}

/** Removes a folder this tool generated (it says so in its README), so that art that left `art/` does not stay in the game. A folder that is not ours is never touched. */
function removeGenerated(outDir: string, result: BuildResult): void {
  const readme = join(outDir, 'README.txt');
  if (existsSync(readme) && readFileSync(readme, 'utf8').startsWith(GENERATED_MARKER)) {
    rmSync(outDir, { recursive: true, force: true });
    result.written.push('(removed the generated folder: no art ships)');
  }
}

export function buildArt(options: BuildOptions): BuildResult {
  const opts = { ...DEFAULT_PACK, ...options.pack };
  const result: BuildResult = { ok: true, packs: [], issues: [], written: [], diskBytes: 0, decodedBytes: 0 };
  const indexFile = join(options.srcDir, 'index.json');
  if (!existsSync(indexFile)) {
    if (options.write) removeGenerated(options.outDir, result);
    // art put by hand in the folder the game fetches still ships: it is checked like any other
    if (existsSync(join(options.outDir, 'index.json'))) {
      const shipped = verifyArtFolder(options.outDir);
      result.issues.push(...shipped.issues);
      result.packs = shipped.packs.map((p) => ({ id: p.id, status: p.status, shipped: true, how: 'copied', sprites: [] }));
      result.ok = shipped.ok;
    }
    return result;
  }
  const raw = readJson(indexFile, 'index.json', result.issues);
  const index = raw === undefined ? null : parseArtIndex(raw);
  if (index) result.issues.push(...tagged('index.json', index.issues.filter((i) => i.level !== 'info')));
  const entries = index?.value?.packs ?? [];

  const outputs: Output[] = [];
  const shipped: ArtIndexEntry[] = [];
  for (const entry of entries) {
    const { built, outputs: files, manifest } = buildPack(entry, options.srcDir, opts, result.issues);
    result.packs.push(built);
    if (built.shipped && manifest !== null) {
      outputs.push(...files, { rel: entry.manifest, data: manifest });
      shipped.push(entry);
    }
  }
  if (shipped.length > 0) {
    outputs.push({ rel: 'index.json', data: json({ manifestVersion: 1, packs: shipped.map((e) => ({ id: e.id, category: e.category, load: e.load, ...(e.zones.length > 0 ? { zones: e.zones } : {}), manifest: e.manifest, ...(e.tags.length > 0 ? { tags: e.tags } : {}) })) }) });
    outputs.push({ rel: 'README.txt', data: `${GENERATED_MARKER}\nThe source is art/: change it there and run the packer again.\n` });
  }
  // what will ship is checked the way the game and `assets:verify` read it — index → manifest → atlases — before a byte is written
  const byRel = new Map(outputs.map((o) => [o.rel, o]));
  result.issues.push(...verifyArt((rel) => {
    const o = byRel.get(rel);
    return o ? (typeof o.data === 'string' ? Buffer.from(o.data) : o.data) : null;
  }).issues);
  result.ok = !result.issues.some((i) => i.level === 'error') && index?.value != null;
  for (const o of outputs) {
    const size = typeof o.data === 'string' ? Buffer.byteLength(o.data) : o.data.length;
    result.diskBytes += size;
  }
  for (const o of outputs) {
    if (!o.rel.endsWith('.png') || typeof o.data === 'string') continue;
    const info = readPngInfo(o.data);
    result.decodedBytes += info.width * info.height * 4;
  }

  if (result.ok && options.write) {
    if (shipped.length === 0) removeGenerated(options.outDir, result);
    else {
      // a folder this tool generated is rewritten whole; a folder that is not ours is never wiped (the build refuses instead)
      if (existsSync(options.outDir)) {
        const readme = join(options.outDir, 'README.txt');
        if (!existsSync(readme) || !readFileSync(readme, 'utf8').startsWith(GENERATED_MARKER)) {
          result.issues.push({ level: 'error', path: options.outDir, message: 'already exists and was not generated by this tool (it has no README.txt saying so): move it away or delete it' });
          result.ok = false;
          return result;
        }
        rmSync(options.outDir, { recursive: true, force: true });
      }
      for (const o of outputs) {
        const file = join(options.outDir, ...o.rel.split('/'));
        mkdirSync(dirname(file), { recursive: true });
        writeFileSync(file, o.data);
        result.written.push(o.rel);
      }
    }
  }
  return result;
}

/** What the build says, for a person. */
export function formatReport(result: BuildResult, write: boolean): string {
  const lines: string[] = [];
  const kb = (n: number): string => `${(n / 1024).toFixed(1)} KB`;
  if (result.packs.length === 0) lines.push('art: nothing to build (no art/index.json): the game keeps its placeholders and ships no art');
  for (const p of result.packs) {
    const what = p.how === 'awaiting' ? 'awaiting art — checked, NOT shipped' : `${p.how === 'copied' ? 'copied as packed by the artist' : 'packed'}, ${p.shipped ? 'shipped' : 'NOT shipped'}`;
    lines.push(`pack ${p.id} [${p.status}] — ${what}`);
    for (const s of p.sprites) lines.push(`  ${s.id}: ${s.frames} frames, ${s.stored} stored (${s.frames - s.stored} repeated), ${s.pages} page(s), ${kb(s.pagePixels * 4)} decoded`);
  }
  for (const i of result.issues) lines.push(`${i.level === 'error' ? 'ERROR' : i.level === 'warn' ? 'warn ' : 'note '} ${i.path}: ${i.message}`);
  if (result.packs.some((p) => p.shipped)) lines.push(`${write ? 'wrote' : 'would write'} ${result.packs.filter((p) => p.shipped).length} pack(s): ${kb(result.diskBytes)} on disk, ${kb(result.decodedBytes)} once decoded`);
  lines.push(result.ok ? 'art: OK' : 'art: FAILED — nothing was written');
  return lines.join('\n');
}
