import type { Rect } from '@/core/math';
import type { CameraConfig } from '@/camera/CameraRig';

/**
 * A room, as data. Grows phase by phase (enemies in F7, environment in F8, gates/secrets in F9…) but every
 * addition is OPTIONAL, so a room written today keeps working. Authoring guide: docs/guides/create-room.md.
 *
 * Coordinates: metres, +X right, +Y up, gameplay plane z = 0. Rects are { x0, y0, x1, y1 } with x0 < x1, y0 < y1.
 */

export interface SolidDef {
  /** Unique within the room. Auto-generated by builders when omitted. */
  id: string;
  rect: Rect;
  /** `solid` blocks from all sides; `oneway` is a jump-through platform. */
  kind?: 'solid' | 'oneway';
  /** Visual material preset for the environment builder (`stone`, `earth`, `wood`, `moss`…). */
  material?: string;
  /** Gameplay label (gates and breakables use it to find their collider). */
  tag?: string;
}

export interface EntryDef {
  id: string;
  /** Feet position where the player appears. */
  x: number;
  y: number;
  facing?: 1 | -1;
}

export interface RoomDefinition {
  id: string;
  regionId: string;
  /** Display name (localised through the UI string table in the UI layer). */
  name: string;
  /** Room extents; also the default camera bounds. */
  bounds: Rect;
  solids: SolidDef[];
  entries: EntryDef[];
  /** Below this Y the player has fallen out of the world (damage + respawn at the last safe ground). */
  killY?: number;
  camera?: Partial<CameraConfig> & { bounds?: Rect };
}
