import type { Rect } from '@/core/math';
import type { CameraConfig } from '@/camera/CameraRig';
import type { InteractableDef } from '@/interaction/Interactable';

/**
 * A room, as data. Grows phase by phase (enemies in F7, environment in F8, gates/secrets in F9…) but every
 * addition is OPTIONAL, so a room written today keeps working. Authoring guide: docs/guides/create-room.md.
 *
 * Coordinates: metres, +X right, +Y up, gameplay plane z = 0. Rects are { x0, y0, x1, y1 } with x0 < x1, y0 < y1.
 */

export interface SolidDef {
  /** Unique within the room. Auto-generated by builders when omitted. */
  id: string;
  rect: Rect;
  /** `solid` blocks from all sides; `oneway` is a jump-through platform. */
  kind?: 'solid' | 'oneway';
  /** Visual material preset for the environment builder (`stone`, `earth`, `wood`, `moss`…). */
  material?: string;
  /** Gameplay label (gates and breakables use it to find their collider). */
  tag?: string;
}

export interface EntryDef {
  id: string;
  /** Feet position where the player appears. */
  x: number;
  y: number;
  facing?: 1 | -1;
}

/** An enemy the room places in the world when it is built (data: `RoomRuntime` reads it, docs/ARCHITECTURE-2D.md §5.11). */
export interface SpawnDef {
  /** Unique within the room. */
  id: string;
  /** Id of the `EnemyDefinition` to place. */
  enemy: string;
  /** Feet position. */
  x: number;
  y: number;
  facing?: 1 | -1;
  /**
   * World flag set when this enemy is defeated. While the flag is set the enemy is NOT placed again: the way it guarded
   * stays open through deaths and reloads. Without it, the enemy comes back every time the room is built (§9.2.5).
   */
  defeatFlag?: string;
}

/** A door that is closed until a world flag is set. It is one of the room's `solids`, switched off while open. */
export interface GateDef {
  /** Unique within the room. */
  id: string;
  /** Id of the solid (in `solids`) that blocks while the gate is closed. */
  solid: string;
  /** The gate is open while this world flag is set. */
  openWhen: string;
}

/** Where a way out leads: a room and one of ITS entries (a spawn point). */
export interface Destination {
  room: string;
  entry: string;
}

/**
 * A way out: touching its zone raises `exit:reached` and, when it has a destination, starts the room transition (fade out,
 * load the destination, put the player at the entry it names, fade in: docs/PROMPT6-LOG.md S23). An exit without `to` only
 * raises the event (the test rooms, and `end`).
 */
export interface ExitDef {
  /** Unique within the room. */
  id: string;
  /** The trigger zone. */
  rect: Rect;
  /** Where it leads: the room and the entry the player appears at (never assumed to be the middle of anything). */
  to?: Destination;
  /** The way out of the WORLD as it stands (the end of the slice): it leads nowhere, so a room of the world may have one exit like this without `to`. */
  end?: boolean;
  /**
   * The way is shut while this world flag is NOT set: the zone does nothing (a door of the world that something has to open).
   * It mirrors the physical gate in the room; the world validator uses it to prove the whole world can be finished.
   */
  requires?: string;
}

/** What a hazard is. The interface draws it by kind; `spikes` is the one that exists today. */
export type HazardKind = 'spikes';

/**
 * A danger that is part of the room and hurts whoever touches it (docs/PROMPT6-LOG.md S25). It is not an enemy: it has no health, no brain
 * and no telegraph — its zone simply hurts the hero while they stand in it. It hurts through the COMBAT system, so every rule of a hit
 * applies as it is: damage, the knockback away from the zone, stun, hit-stop, the i-frames that follow (a second touch during them does
 * nothing) and the usual events. A pit is not one: falling out of the world is `killY`.
 */
export interface HazardDef {
  /** Unique within the room. */
  id: string;
  kind: HazardKind;
  /** The zone that hurts, world metres. */
  rect: Rect;
  /** Points of life each hit takes (default 1). */
  damage?: number;
}

export interface RoomDefinition {
  id: string;
  regionId: string;
  /** Working name (debug panel, logs). The name the PLAYER reads is `nameKey`, a text key. */
  name: string;
  /** Text key of the localised display name (`room.r1.name`): texts live in the catalogs, never in the content. */
  nameKey?: string;
  /** Room extents; also the default camera bounds. */
  bounds: Rect;
  solids: SolidDef[];
  entries: EntryDef[];
  /** Below this Y the player has fallen out of the world (damage + respawn at the last safe ground). */
  killY?: number;
  camera?: Partial<CameraConfig> & { bounds?: Rect };
  /** Enemies placed when the room is built. */
  spawns?: SpawnDef[];
  /** Doors that open with world flags. */
  gates?: GateDef[];
  /** Ways out of the room. */
  exits?: ExitDef[];
  /** Things the player can interact with: pickups, levers… (docs/GAME-SPEC-2D.md §12). Rewards write world flags. */
  interactables?: InteractableDef[];
  /** Zones that hurt the hero: spikes (docs/PROMPT6-LOG.md S25). */
  hazards?: HazardDef[];
  /** Provisional scenery behind and in front of the action (never collision): `render/backdrops` draws it. */
  art?: { backdrop: string; seed?: number };
}
